### ISSUE TITLE
Configure wallet connect to use Base chain on the rainbowKit wallet.

### ISSUE THREAD

**Issue by sudoFerraz** [armitage-labs/armitage-monorepo#120]
Create and configure new WalletConnect keys that provide access to the Base chain.

Note that with the support of Base, we also need to refactor and modify the code that creates new Private attestations, as they currently only support Ethereum Sepolia;
This likely includes:
- Making sure that the provider for Base can be selected by the user when creating a new private attestation;
- Making sure that the frontend client can understand which chain the user has selected, and choose the correct schemaID of that chain (look for private data schema ID) -> currently we only have the Sepolia one hardcoded.

**Comment by AlecErasmus** [comment]
Started working on this
