### ISSUE TITLE
Create new schema for public onchain attestations of contributor scores

### ISSUE THREAD

**Issue by sudoFerraz** [armitage-labs/armitage-monorepo#121]
We should create a new schema for onchain attestations of contributor scores.

This is necessary for integrations with new chains and other applications;
The schemaIDs of these new schemas should be saved on the application configuration and mapped to which specific chains they point to;

Feel free to create this configuration as a .env variable, a json or yaml file.

e.g.:
`
attestationPublicSchemaIds:
    base: 0x2137839
    sepolia: 0x12384
    optimism: 0x1234
etc...
`

These schemas should follow the following structure:

```
githubUsername;
measuredAt;
weightsConfig;
repositoryName;
organizationName;
userScores
```

**Comment by AlecErasmus** [comment]
Schema format:

string githubUsername,string measuredAt,string repositoryName,string organizationName,string prNodeWeight,string prReviewNodeWeight,string issueNodeWeight,string commentNodeWeight,string reactionNodeWeight,string userScoreRank,string userCredScore,string userCredScorePercentage

**Comment by AlecErasmus** [comment]
reactionNodeWeight is not supported, being replaced with commitNodeWeight
